convert.py
src/code.rs
src/key.rs

This adds the missing `F13` - `F24` values, adds aliases for various values that are still used in Firefox and Safari and adds some values that are only used by Chromium.
Resolves #12
Resolves #13
Resolves #14

Adjust `Code` to match the actual browsers

---

Cargo.toml
README.md

The badges section of a Cargo.toml no longer needs build status badges as they are no longer supported by crates.io.

Update build status, remove Cargo.toml badge.

---

Cargo.toml

This is the earliest version that compiles as transitive deps require this.

Set rust-version (MSRV) to 1.56.

---

Cargo.toml
src/modifiers.rs

This requires enabling a "serde" feature when the `keyboard-types` "serde" feature is enabled.

deps: Update to bitflags 2.

---

src/modifiers.rs

Add `shift`, `ctrl`, `alt`, `meta` utilities on `Modifiers`.

---

Cargo.toml
convert.py
src/code.rs
src/key.rs
src/lib.rs
src/location.rs
src/modifiers.rs
src/shortcuts.rs
src/webdriver.rs

This leaves `extern crate` usage which can be removed in subsequent commits.

Update to Rust edition 2018.

---

.github/workflows/ci.yml
Cargo.toml

This also combines the jobs into one since they run quickly and this reduces the overhead of installing deps for each step.

ci: Check MSRV, bump to 1.60 and improve feature coverage.

---

.github/workflows/ci.yml

This mainly keeps up with the current version of Node within the GitHub Actions infrastructure.

ci: Update to `actions/checkout@v4` from v3.

---

.github/workflows/ci.yml
Cargo.toml

Half of #47.
I have verified that `keyboard-types` does actual compile on `1.61`

Bump MSRV to 1.61

---

convert.py
src/code.rs
src/key.rs
src/lib.rs
src/location.rs
src/webdriver.rs

Allows using these types in `BTreeMap`/`BTreeSet`.
Note that we do not guarantee anything about the ordering between SemVer-compatible versions of the crate.
See also:
- https://github.com/rust-windowing/winit/pull/2918
- https://github.com/rust-windowing/winit/pull/2998
- https://github.com/rust-windowing/winit/pull/3796
(And https://github.com/rust-windowing/winit/pull/3866 for the case where `PartialOrd`/`Ord` wouldn't make sense).
Part of #19.

Add `PartialOrd` and `Ord` implementations

---

src/lib.rs

Instead of `Display`, we expose an inherent method, since that allows using in more contexts (the return type is now a static str), and because it's semantically more correct IMO (the composition state isn't intrinsically tied to being the event type).
Not that important, but I felt it made sense to do together with https://github.com/pyfisch/keyboard-types/pull/53.

Remove `Display` impl on `CompositionState`, and add more docs

---

convert.py
src/code.rs
src/key.rs
src/location.rs

Fixes https://github.com/pyfisch/keyboard-types/issues/47.
I chose to ignore the lints, since the documentation is auto-generated, and thus hard to control.

Appease clippy

---

README.md
convert.py
src/code.rs
src/key.rs

Fixes `Period` docs having invalid HTML, `Eject` docs containing a link, and allows us to more easily parse more stuff in the future.

Parse using BeautifulSoup

---

convert.py
src/code.rs

This is useful to have when searching.
I filed https://github.com/w3c/uievents-code/pull/44 to get the backquote part upstream, but that hasn't seen much movement, so I thought I'd fix it here for now.

Note alternative names of `Code::Backquote` and `Code::Quote`

---

convert.py
src/code.rs
src/key.rs
src/modifiers.rs
src/webdriver.rs

This resolves my concern with `Meta` vs. `Super` from https://github.com/pyfisch/keyboard-types/issues/19.

Mark legacy modifier keys and codes as deprecated

---

src/lib.rs
src/shortcuts.rs

Remove `Display` impl, rename variants and add helper methods, see each commit for details.
The motivation is to make this match [`winit::event::ElementState`](https://docs.rs/winit/0.30.5/winit/event/enum.ElementState.html).
Unsure about the helper method names, whether `is_pressed` or `pressed` is cleaner? I went with `is_pressed` to match what's used in the wild for e.g. Bevy's [`ButtonState`](https://docs.rs/bevy/0.15.0/bevy/input/enum.ButtonState.html), and since it also more closely matches Rust conventions on enums (`is_some`, `is_poisoned`, `is_ne`, ...). But that's inconsistent with e.g. `Modifiers::shift` (so maybe we should change the latter too?).

Change `KeyState`

---

convert.py
src/code.rs
src/lib.rs
src/named_key.rs
src/shortcuts.rs
src/webdriver.rs

This makes most of the key `Copy`, and allows other crates like Winit to more easily use their own string types.
See https://github.com/rust-windowing/winit/issues/2995 and https://github.com/rust-windowing/winit/pull/3143 for discussion on a similar change in Winit.
Part of https://github.com/pyfisch/keyboard-types/issues/19.

Separate `Key` into `Character` and `NamedKey`

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs

I suspect most users will not want these enabled, but it's very easy to accidentally do so when depending on `keyboard-types`. Not that it's a _big_ problem, because both deps are small and trusted, but it's still a bit annoying.
I've also enabled `doc_auto_cfg` to ensure that the docs on docs.rs make it clear that feature flags are required to enable these.

Remove `serde` and `webdriver` from `default` features

---

convert.py
src/code.rs
src/named_key.rs

From discussion in https://github.com/rust-windowing/winit/pull/4018#discussion_r1865821387. Happy to take suggestions on the wording.
Related to https://github.com/pyfisch/keyboard-types/pull/49.

Note that "super" is often emitted as `Meta` on Linux

---

Cargo.toml
convert.py
src/code.rs
src/lib.rs
src/named_key.rs

Since `core::error` isn't in Rust until 1.81, we can't use it and so we only derive `Error` for the error types when building with the `std` feature.
Also, `webdriver` implies `std` as well (for now?).

Initial `no_std` support

---

convert.py
src/code.rs
src/named_key.rs

For certain keys and codes where it makes sense, including those we already have alternatives for when parsing.
Fixes #64. Assumes that the meta->super change in https://github.com/pyfisch/keyboard-types/pull/68 will land.
It looks like this when searching:
But doesn't show up in the documentation otherwise (so https://github.com/pyfisch/keyboard-types/pull/68 is still valuable).

Add `#[doc(alias = ...)]` attributes

---

.github/workflows/ci.yml
Cargo.toml
README.md
convert.py
src/code.rs
src/named_key.rs

To get access to `core::error::Error`.
Alternative to https://github.com/rust-windowing/keyboard-types/pull/70.
Not sure how much I like it, I'd also be fine with doing nothing here. But I'd definitely rather do this than raise MSRV for everyone.

Raise MSRV to 1.81 on `no_std`

---

convert.py
src/code.rs
src/lib.rs
src/named_key.rs
src/shortcuts.rs

This fixes a couple of typos and links some identifiers.

Doc tweaks / improvements

---

src/lib.rs

Part of https://github.com/rust-windowing/keyboard-types/issues/80.
This is a common pattern to allow more easily constructing "wrapper" enums like `Key` is. An example of this pattern is [`impl From<std::net::Ipv4Addr> for std::net::IpAddr`](https://doc.rust-lang.org/std/net/enum.IpAddr.html#impl-From%3CIpv4Addr%3E-for-IpAddr).

Add `impl From<NamedKey> for Key`

---

src/named_key.rs

This is a common point of confusion, see https://github.com/rust-windowing/keyboard-types/issues/82.

Make it clear in the docs that space is not a named key

---

Cargo.toml

Only functional difference since v0.8.0 is https://github.com/rust-windowing/keyboard-types/pull/81, the rest is documentation improvements and nits.

Release v0.8.1

---

src/webdriver.rs

For webdriver, converting the code for `NumpadEqual` and `Pause`, also the key location for `NumpadEqual`.
Spec:
https://w3c.github.io/webdriver/#dfn-code
https://w3c.github.io/webdriver/#dfn-key-location

Fix NumpadEqual and Pause code and location for WebDriver

---

src/composition.rs
src/key.rs
src/key_state.rs
src/keyboard_event.rs
src/lib.rs
src/location.rs

This makes the code slightly more readable.
This is a move-only PR with no change in behavior.

Split `lib.rs` into multiple files

---

src/lib.rs

Fixes https://github.com/rust-windowing/keyboard-types/issues/92.
Tested with:
```sh
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --open --all-features
```

Use `doc_cfg` instead of `doc_auto_cfg`
